export const GET_ERRORS = 'GETTING ERRORS';
export const CLEAR_ERRORS = 'CLEARING ERRORS';
export const SET_USER = 'SETTING CURRENT USER';
export const USER_LOADING = 'LOADING USER INFORMATION';
export const ADD_BANK_ACCOUNT = 'CREATING NEW BANK ACCOUNT';
export const ACCOUNT_ACTION_LOADING = 'LOADING ACCOUNT';
export const FETCH_ALL_BANK_ACCOUNTS = 'GETTING ALL BANKA ACCOUNTS';
